apiVersion: v1     
kind: Pod                            
metadata:
  name: webserver-v2
  namespace: ns1
  labels:
    app: webserver
    version: v2
spec:
  containers:
  - name: webserver
    image: nginx:1.27
    ports:
    - containerPort: 80
